name: Add changeset automatically

on:
  pull_request_target:
    types:
      - opened
      - edited
      
# startsWith(github.repository, 'asyncapi/') &&
jobs:
  auto-changeset:
    if: |
      ( startsWith(github.event.pull_request.title, 'fix:') ||
        startsWith(github.event.pull_request.title, 'feat:') ||
        startsWith(github.event.pull_request.title, 'fix!:') ||
        startsWith(github.event.pull_request.title, 'feat!:')
      )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}
      - name: Determine release type
        id: determine_release_type
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title;
            const releaseType = title.split(':')[0];
            switch (releaseType) {
              case 'fix':
                return 'patch';
              case 'feat':
                return 'minor';
              case 'fix!':
                return 'major';
              case 'feat!':
                return 'major';
              default:
                return 'patch';
            }
      - name: Create changeset file
        run: "echo -e '---\n'@asyncapi/cli': ${{ steps.determine_release_type.outputs.result }}\n---\n\n ${{ github.event.pull_request.title }}\n\n' > .changeset/${{ github.event.pull_request.number }}.md"
      - name: Commit changeset file
        run: |
          git config --global user.email "info@asyncapi.com"
          git config --global user.name "asyncapi-bot"
          git add .changeset/${{ github.event.pull_request.number }}.md
          git commit -m "chore: add changeset for PR #${{ github.event.pull_request.number }}"
      # - name: Debug event
      #   run: echo ${{ toJson(github.event) }}
      - name: Push changeset file
        run: git push https://${{ secrets.GH_TOKEN }}@github.com/${{ github.event.pull_request.head.repo.full_name }} HEAD:${{ github.event.pull_request.head.ref }}